title: Shafanda Nabil Sembodo | Data Scientist Consultant
description: Full-stack Data Scientist Consultant with 4+ years of experience transforming raw data into actionable insights.
url: https://fandanabil1379.github.io
include:
  - index.html
  - assets
